services:
  app-main:
    build: ./app
    restart: always
    environment:
      - SERVICE_TYPE=main
      - PORT=${MAIN_PORT}
    networks:
      - backend

  app-health:
    build: ./app
    restart: always
    environment:
      - SERVICE_TYPE=health
      - PORT=${HEALTH_PORT}
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app-main
      - app-health
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge